name: Release on tag to the main site

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: https://ci.dsp-calc.pro/actions/checkout@v4
      
      - run: npm install
      - run: npm run build
      
      - name: publish to netlify.app
        run: netlify deploy --dir dist --prod-if-unlocked
        env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
